#!/usr/bin/python3
from math import sqrt
import sys

def factors(n):
    factors = []
    for i in range(2, int(n ** 0.5) + 1):
        if n % i == 0:
            factors.extend([i, n // i])
            return f"{n}={n//i}*{i}"
    return None
file = open(sys.argv[1], 'r')

for num in file:
    try:
        result = factors(int(num))
        if result:
            print(result)
    except:
        pass
